responsive design, navbar, and footer improvements
labdao/labdao.xyz pull request #42
Opened 2022-10-22 16:53 UTC by cwest144

- improve the navbar, including responsive design fixes
- add a footer
- move privacy policy to footer

2022-10-22 17:20 UTC, jlevers commented
@NiklasTR do you want us to add the snapshot logo/link to the nav of labdao.xyz to mirror the igem.labdao.xyz nav design?

2022-10-22 17:44 UTC, jlevers requested changes

2022-10-22 17:44 UTC, jlevers commented on src/lib/layouts/Footer.svelte
> +          <a href="/privacy-policy">Privacy Policy</a>
let's put these links under the LabDAO logo in the footer -- since there's currently only one of them, it looks kinda strange in a column by itself

2022-10-22 17:44 UTC, jlevers commented on src/lib/components/shared/MenuDesktop.svelte
> +        <img src={logo} alt="SvelteKit" class="w-40 md:w-auto" />
this `alt` should be `Labdao logo`

2022-10-22 17:44 UTC, jlevers commented on src/lib/components/shared/MenuDesktop.svelte
> +      <button type="button" aria-description="Closes social media menu" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-md border-2 shadow-lg lg:hidden hover:bg-gray-100 focus:
let's put the different attrs on multiple lines to make this more readable:

```html
<button
  type="button"
  aria-description="Closes social media menu"
  class="..."
  on:click={...}
>
```

2022-10-22 17:44 UTC, jlevers commented on src/lib/components/shared/MenuDesktop.svelte
> +        <span class="sr-only">Open social media menu</span>
ah that's a cool class

2022-10-22 17:44 UTC, jlevers commented on src/lib/components/shared/MenuDesktop.svelte
> +      <button type="button" aria-description="Opens social media menu" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-md border-2 border-white lg:hidden hover:bg-gray-100 focu
ditto multi-line attrs comment

2022-10-22 17:44 UTC, jlevers commented on src/lib/components/shared/MenuDesktop.svelte
> +<header class="menu-desktop relative flex items-center justify-between leading-6 px-5 xl:px-24 z-index:10">
what's the purpose of the z-index here?

2022-10-22 17:44 UTC, jlevers commented on src/lib/components/shared/MenuDesktop.svelte
> +      <div class="w-full w-auto flex flex-col absolute top-16 lg:top-0 right-5 lg:right-0 sm:right-12 md:right-24 bg-white p-2 lg:p-0 rounded border-2 lg:border-0 shadow-lg lg:shadow-none lg:rounded-
since this is only visible at sizes `lg` and above, i don't think the `lg:*` and `sm:*` classes are necessary -- you can remove the `lg:` part from the `lg:*` classes, and then remove the default class (the one without a breakpoint selector), and you can remove the `sm:*` classes altogether

2022-10-23 13:50 UTC, cwest144 commented on src/lib/components/shared/MenuDesktop.svelte
> +<header class="menu-desktop relative flex items-center justify-between leading-6 px-5 xl:px-24 z-index:10">
i added it when I was trying to make the social media appear above the page content, but it looks like a different change I made is what actually fixed that problem. I removed the `z-index` here.

2022-10-24 17:57 UTC, jlevers requested changes
looks good -- last thing is that these buttons look weird at small screen sizes. i think best solution is to make them both full width (minus margins) and have the text in them centered

<img width="184" alt="image" src="https://user-images.githubusercontent.com/4974856/197593671-48fdedcc-6882-43e8-9947-f42d87dd9ab2.png">

2022-10-25 15:45 UTC, merged